# Generated by Django 4.1.7 on 2023-03-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Slider name')),
                ('img', models.ImageField(upload_to='images', verbose_name='Slider image')),
                ('verify_button', models.BooleanField(verbose_name='Slider verify button Show/Hide')),
                ('verify_logo', models.ImageField(upload_to='images', verbose_name='Slider verify logo')),
                ('link_1', models.URLField(blank=True, verbose_name='Slider link1')),
                ('link_2', models.URLField(blank=True, verbose_name='Slider link2')),
                ('link_3', models.URLField(blank=True, verbose_name='Slider link3')),
                ('link1_name', models.CharField(blank=True, max_length=100, verbose_name='Slider link1 name')),
                ('link2_name', models.CharField(blank=True, max_length=100, verbose_name='Slider link2 name')),
                ('link3_name', models.CharField(blank=True, max_length=100, verbose_name='Slider link3 name')),
                ('proff1', models.CharField(blank=True, max_length=50, verbose_name='Proff1 name')),
                ('proff2', models.CharField(blank=True, max_length=50, verbose_name='Proff2 name')),
            ],
        ),
    ]
