# Generated by Django 4.1.7 on 2023-03-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homefooterbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Last_episode name')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_episode', to='main.homeslider')),
            ],
        ),
    ]
